#pragma once

#include <array>

#include <NEMain.h>

enum class ModelId : u8
{
    // Forest
    Ground,
    TreeRound,
    TreeGolden,
    TreeFir,
    Bush,
    Rock,
    Stump,
    Shrine,
    Shadow,
    LeafA,
    LeafB,
    LeafC,
    // Characters
    NinaHead,
    NinaBody,
    NinaArm,
    NinaLeg,
    MatsHead,
    MatsBody,
    MatsArm,
    MatsLeg,
    // Mushrooms (world versions)
    Steinpilz,
    SatansRoehrling,
    Champignon,
    Knollenblaetterpilz,
    Pfifferling,
    Fliegenpilz,
    OelbaumTrichterling,
    WaldgottPilz,
    // Items
    Basket,
    Scarf,
    Lantern,
    LanternGlass,
    Bell,
    LightDisc,
    WoolHat,
    // Mushrooms (detailed, for the inspection view)
    DetailSteinpilz,
    DetailSatansRoehrling,
    DetailChampignon,
    DetailKnollenblaetterpilz,
    DetailPfifferling,
    DetailFliegenpilz,
    DetailOelbaumTrichterling,
    DetailWaldgottPilz,
    // Shroomchen, the forest god
    CowBody,
    CowLeg,
    CowCrown,
    // Final picture
    EndHill,
    Count,
};

// Loads and owns all 3D models and materials from NitroFS.
// Every model shares the palette texture generated by assets/blender/dsmesh.py;
// glowing models use a clone of it that only shows its emission.
class AssetService
{
public:
    // Requires an initialised 3D engine (RenderService::Init).
    void LoadAll();

    NE_Model *Model(ModelId id) const { return models_[static_cast<size_t>(id)]; }
    NE_Material *PaletteMaterial() const { return palette_; }
    // Same texture, emission only: for models drawn with Lighting::Glow.
    NE_Material *GlowMaterial() const { return glow_; }

    // True for models that must be drawn unlit (RenderService Lighting::Glow).
    static bool IsGlowing(ModelId id);
    // Glowing part drawn together with a model (lantern glass), or ModelId::Count.
    static ModelId GlowPartOf(ModelId id);

private:
    std::array<NE_Model *, static_cast<size_t>(ModelId::Count)> models_ = {};
    NE_Material *palette_ = nullptr;
    NE_Material *glow_ = nullptr;
};
